TourBookingWeb/Areas/Admin/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace TourBookingWeb.Areas.Admin.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }

}

TourBookingWeb/Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TourBookingWeb.Data;
using NLog;
using X.PagedList;
using X.PagedList.EF;
using TourBookingWeb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TourBookingWeb.Controllers
{
    public class TourController : Controller
    {
        private readonly TourDBContext _ctx;
        private static Logger logger = LogManager.GetCurrentClassLogger();
        public TourController(TourDBContext ctx)
        {
            _ctx = ctx;
        }
        public async Task<IActionResult> Index(
                    string? keyword, int? categoryId,
                    string? destination, DateTime? departureDate,
                    int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 9;

            /* ---- truy vấn gốc ---- */
            var query = _ctx.Tours
                            .Include(t => t.Schedules)
                            .AsQueryable();

            /* ---- áp dụng filter ---- */
            if (!string.IsNullOrWhiteSpace(keyword))
                query = query.Where(t => t.Title.Contains(keyword));

            if (categoryId is > 0)
                query = query.Where(t => t.CategoryId == categoryId);

            if (!string.IsNullOrWhiteSpace(destination))
                query = query.Where(t => t.Destination.Contains(destination));

            if (departureDate.HasValue)
                query = query.Where(t => t.Schedules
                                    .Any(s => s.DepartureDate.Date ==
                                              departureDate.Value.Date));

            /* ---- phân trang ---- */
            var paged = await query
                            .OrderBy(t => t.Title)
                            .ToPagedListAsync(pageNumber, pageSize);

            /* ---- dữ liệu cho dropdown ---- */
            ViewBag.Categories = await _ctx.Categories
                    .Select(c => new SelectListItem
                    {
                        Value = c.CategoryId.ToString(),
                        Text = c.CategoryName
                    }).ToListAsync();

            ViewBag.Destinations = await _ctx.Tours
                    .Select(t => t.Destination)
                    .Distinct()
                    .OrderBy(d => d)
                    .ToListAsync();

            /* để đổ ngược lại ô tìm kiếm */
            ViewBag.Keyword = keyword;
            ViewBag.CategoryId = categoryId ?? 0;
            ViewBag.Destination = destination;
            ViewBag.DepartureDate = departureDate?.ToString("yyyy-MM-dd");

            return View(paged);
        }

        // -----------  AJAX -------------
        [HttpGet]
        public async Task<IActionResult> SearchJson(
            string? keyword, int? categoryId,
            string? destination, DateTime? departureDate,
            int page = 1, int pageSize = 9)
        {
            var q = _ctx.Tours
                        .Include(t => t.Schedules)   // cần để lọc + lấy ngày
                        .AsQueryable();

            if (!string.IsNullOrWhiteSpace(keyword))
                q = q.Where(t => t.Title.Contains(keyword));

            if (categoryId is > 0)
                q = q.Where(t => t.CategoryId == categoryId);

            if (!string.IsNullOrWhiteSpace(destination))
                q = q.Where(t => t.Destination.Contains(destination));

            if (departureDate.HasValue)
                q = q.Where(t => t.Schedules
                                .Any(s => s.DepartureDate.Date ==
                                          departureDate.Value.Date));

            int total = await q.CountAsync();

            var list = await q.OrderBy(t => t.Title)
                              .Skip((page - 1) * pageSize)
                              .Take(pageSize)
                              .Select(t => new
                              {
                                  t.TourId,
                                  t.Title,
                                  t.Destination,
                                  t.Duration,
                                  t.Capacity,
                                  t.AdultPrice,
                                  /* 3 ngày khởi hành đầu tiên */
                                  Departures = t.Schedules
                                                .Where(s => !s.IsDeleted)
                                                .OrderBy(s => s.DepartureDate)
                                                .Take(3)
                                                .Select(s => s.DepartureDate.ToString("dd/MM/yyyy"))
                                                .ToList(),

                                  ImageUrl = _ctx.Images
                                          .Where(i => i.TourId == t.TourId &&
                                                      i.DayNumber == 0)
                                          .Select(i => i.Url)
                                          .FirstOrDefault() ??
                                          "assets/images/no-image.jpg"
                              })
                              .ToListAsync();

            return Json(new
            {
                data = list,
                currentPage = page,
                totalPages = (int)Math.Ceiling(total / (double)pageSize)
            });
        }




        public async Task<IActionResult> Details(int id)
        {
            var tour = await _ctx.Tours
                .Include(t => t.Schedules.Where(s => !s.IsDeleted)) // chỉ lấy lịch trình chưa xóa
                .FirstOrDefaultAsync(t => t.TourId == id);

            if (tour == null)
            {
                logger.Warn($"Không tìm thấy tour ID {id} khi xem chi tiết");
                return NotFound();
            }

            return View(tour);
        }


        [HttpPost]
        public IActionResult BookNow(int tourId, string departureDate)
        {
            return RedirectToAction("Create", "Booking", new
            {
                tourId = tourId,
                departureDate = DateTime.ParseExact(departureDate, "dd/MM/yyyy", null)
            });
        }



    }
}

TourBookingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - Tourist</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- Icon -->
    <link rel="icon" type="image/png" href="~/img/icons/favicon.png" />

</head>
<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <!-- Topbar Start -->
    <div class="container-fluid bg-dark px-5 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <small class="me-3 text-light"><i class="fa fa-map-marker-alt me-2"></i>Nguyễn Hữu Thọ, Quận 7, TPHCM</small>
                    <small class="me-3 text-light"><i class="fa fa-phone-alt me-2"></i>0559960019</small>
                    <small class="text-light"><i class="fa fa-envelope-open me-2"></i>hongphuc31122306@gmail.com</small>
                </div>
            </div>
            <div class="col-lg-4 text-center text-lg-end">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="#"><i class="fab fa-instagram fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="#"><i class="fab fa-youtube fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href="#"><i class="fa fa-envelope fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid position-relative p-0">
        <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
            <a href="/" class="navbar-brand p-0">
                <h1 class="text-primary m-0"><i class="fa fa-map-marker-alt me-3"></i>Tourist</h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0">
                    <a asp-controller="Home" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"]?.ToString() == "Home" ? "active" : "")">Trang chủ</a>
                    <a asp-controller="Tour" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"]?.ToString() == "Tour" ? "active" : "")">Tours</a>
                    <a asp-controller="Contact" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"]?.ToString() == "Contact" ? "active" : "")">Liên hệ</a>
                    @if (User.Identity.IsAuthenticated)
                    {
                            <a asp-controller="Account" asp-action="Profile" class="nav-item nav-link">Tài khoản</a>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Register" class="nav-item nav-link">Đăng ký</a>
                    }
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <form asp-controller="Account" asp-action="Logout" method="post" class="d-inline">
                        <button type="submit" class="btn btn-primary rounded-pill py-2 px-4 ms-2">Đăng xuất</button>
                    </form>
                }
                else
                {
                    <a asp-controller="Account" asp-action="Login" class="btn btn-primary rounded-pill py-2 px-4 ms-2">Đăng nhập</a>
                }
            </div>
        </nav>
    </div>
    <!-- Navbar End -->
   
    <!-- Nội dung trang -->
    <div class="container-fluid p-0">
        @RenderBody()
    </div>
    <a id="backToTopBtn" href="#" class="back-to-top" title="Trở về đầu trang">
        <img src="/img/icons/up-arrow-green.png" alt="↑" style="width: 30px; height: 30px;">
    </a>


    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Về chúng tôi</h4>
                    <a class="btn btn-link" href="">Giới thiệu</a>
                    <a class="btn btn-link" href="">Liên hệ</a>
                    <a class="btn btn-link" href="">Chính sách bảo mật</a>
                    <a class="btn btn-link" href="">Điều khoản</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Nguyễn Hữu Thọ, Quận 7, TPHCM</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>0559 960 019</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>hongphuc31122306@gmail.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social me-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social me-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social me-2" href="#"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Gallery</h4>
                    <img class="img-fluid mb-2 me-2" src="/img/background/bg1.jpg" style="width: 80px; height: 60px;" />
                    <img class="img-fluid mb-2 me-2" src="/img/background/bg2.jpg" style="width: 80px; height: 60px;" />
                    <img class="img-fluid mb-2 me-2" src="/img/background/bg3.jpg" style="width: 80px; height: 60px;" />
                    <img class="img-fluid mb-2 me-2" src="/img/background/bg4.jpg" style="width: 80px; height: 60px;" />
                    <img class="img-fluid mb-2 me-2" src="/img/background/bg5.jpg" style="width: 80px; height: 60px;" />
                    <img class="img-fluid mb-2 me-2" src="/img/background/bg6.jpg" style="width: 80px; height: 60px;" />
                </div>

                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Newsletter</h4>
                    <p>Hãy để lại email để nhận thông tin mới nhất về tour hấp dẫn từ chúng tôi.</p>
                    <div class="position-relative w-100">
                        <input class="form-control bg-light border-0 w-100 py-3 ps-4 pe-5" type="email" placeholder="Nhập email của bạn">
                        <button type="submit" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Đăng ký</button>
                    </div>
                </div>


            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <script src="~/js/main.js"></script>

    <!-- Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <!-- FontAwesome (nếu chưa có ở trên) -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <!-- Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "timeOut": "3000"
            };

        @if (TempData["Success"] != null)
        {
            <text>toastr.success('@TempData["Success"]');</text>
        }
        @if (TempData["Error"] != null)
        {
            <text>toastr.error('@TempData["Error"]');</text>
        }
        });

        // Hiển thị nút khi cuộn
        window.onscroll = function () {
            const btn = document.getElementById("backToTopBtn");
            if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
                btn.style.display = "block";
            } else {
                btn.style.display = "none";
            }
        };

        // Cuộn lên đầu trang
        document.getElementById("backToTopBtn").addEventListener("click", function (e) {
            e.preventDefault();
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    </script>
    @RenderSection("Scripts", required: false)

</body>
</html>

<style>
    .back-to-top {
        position: fixed;
        bottom: 30px;
        right: 30px;
        display: none;
        z-index: 9999;
        background-color: #8BC34A; /* xanh lá */
        border-radius: 4px;
        padding: 5px;
        box-shadow: 0 2px 6px rgba(0,0,0,0.2);
        transition: all 0.3s ease-in-out;
    }

        .back-to-top:hover {
            transform: scale(1.1);
        }

</style>